version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 18.x
  - dependency-name: eslint-config-prettier
    versions:
    - 8.5.0
  - dependency-name: next-pwa
    versions:
    - 5.6.0
  - dependency-name: eslint
    versions:
    - 8.29.0
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.5.14
  - dependency-name: "@storybook/react"
    versions:
    - 6.5.14
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.16.5
  - dependency-name: "@babel/core"
    versions:
    - 7.20.5
  - dependency-name: jest-styled-components
    versions:
    - 7.1.1
  - dependency-name: eslint-plugin-prettier
    versions:
    - 4.2.1
  - dependency-name: styled-components
    versions:
    - 5.3.6
  - dependency-name: next
    versions:
    - 13.0.6
  - dependency-name: husky
    versions:
    - 8.0.0
  - dependency-name: "@types/jest"
    versions:
    - 29.2.3
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
    - 7.23.1
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 7.31.11
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.26
  - dependency-name: "@types/react"
    versions:
    - 18.0.26
  - dependency-name: typescript
    versions:
    - 4.9.3
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.18.6
  - dependency-name: "@testing-library/react"
    versions:
    - 13.4.0
